{ batch_id: "23", 
actions: [Action { 
    action_name: AddAction, 
    start_time: "2024-07-25T12:00:13", 
    ending_time: "2024-07-25T12:00:17", 
    method_name: "addition", 
    equipment_name: "Chemspeed SWING XL", 
    sub_equipment_name: "GDU-V", 
    container_info: None, 
    speed_shaker: Some(Observation { value: 152.0, unit: "rpm", error_margin: Some(ErrorMargin { value: 1.0, unit: "rpm" }) }), 
    has_container_position_and_quantity: None, 
    dispense_state: Some("Liquid"), 
    dispense_type: Some("volume"), 
    has_sample: Some(Sample { container: ContainerInfo { container_id: "17", container_barcode: "17" }, 
    vial_id: "15", vial_type: "storage vial", role: "solvent", 
    expected_datum: Observation { value: 2.0, unit: "mg", error_margin: None }, 
    has_sample: [SampleItem { sample_id: "123", role: "solvent", internal_bar_code: "1", 
    expected_datum: None, 
    measured_quantity: None, 
    concentration: None, physical_state: "Liquid",
     has_chemical: Chemical { chemical_id: "134", 
     chemical_name: "Toluene", cas_number: "108-88-3", 
     molecular_mass: Observation { value: 92.14, unit: "g/mol", error_margin: None }, 
     smiles: "CC1=CC=CC=C1", swiss_cat_number: "", inchi: "1S/C7H8/c1-7-5-3-2-4-6-7/h2-6H,1H3", 
     keywords: None, molecular_formula: "C7H8", density: Some(Observation { value: 0.8623, unit: "g/mL", 
     error_margin: None }) } }] }), speed_tumble_stirrer: None, temperature_tumble_stirrer: None, temperature_shaker: None }],
      batch_name: None, reaction_type: None, optimization_type: None, link: None }