use lazy_static::lazy_static;
use sophia::api::ns::Namespace;
use sophia_api::namespace;
namespace! {
    "http://example.org/cat#",
    AddAction,
    Batch,
    Campaign,
    ContainerPositionAndQuantity,
    Experiment,
    FiltrateAction,
    Observation,
    Sample,
    SetPressureAction,
    SetTemperatureAction,
    SetVacuumAction,
    ShakeAction,
    speedTumbleStirrerShape,
    campaignClass,
    genericObjective,
    casNumber,
    chemicalName,
    containerBarcode,
    containerID,
    criteria,
    dispenseType,
    errorMargin,
    expectedDatum,
    hasBatch,
    hasCampaign,
    campaignType,
    hasObjective,
    hasContainerPositionAndQuantity,
    hasSample,
    hasChemical,
    internalBarCode,
    measuredQuantity,
    Objective,
    role,
    setTemperatureAction,
    speedInRPM,
    subEquipmentName,
    swissCatNumber,
    temperatureShakerShape,
    temperatureTumbleStirrerShape,
    vialShape,
    reactionType,
    optimizationType,
    reactionSubType
}
lazy_static! {
    pub static ref ns: Namespace<&'static str> = Namespace::new(PREFIX.as_str()).unwrap();
}
