name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - feat/add-nix-package
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run Nix development shell and build/push image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nix develop ./tools/nix#default --accept-flake-config --command bash -c '
            echo "$GITHUB_TOKEN" | skopeo login ghcr.io -u $GITHUB_ACTOR --password-stdin
            just --unstable docker build-nix-package
            just --unstable docker build-nix-image
            just --unstable docker push-image
          '
